---
- hosts: host1
  become: yes
  name: Play 1
  tasks:
     - name: Install apache2
       apt: name=apache2 state=latest
- hosts: host2
  name: Play 2
  become: yes
  tasks:
     - name: Install nginx
       apt: name=nginx state=latest