---
- hosts: host1
  become: yes
  name: Play 1
  tasks:
     - name: Execute command ‘Date’
       command: date
     - name: Execute script on server
       script: test_script.sh
- hosts: host2
  name: Play 2
  become: yes
  tasks:
     - name: Execute script on server
       script: test_script.sh
     - name: Install nginx
       apt: name=nginx state=latest
